name: CI

on:
  push:
  pull_request:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and test (Linux profile)
        run: |
          mvn -B -ntp -q clean test
          mvn -B -ntp -q -Pjlink clean javafx:jlink

  windows-compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Compile with Windows JavaFX profile
        shell: bash
        run: |
          mvn -B -ntp -q -Pwindows -DskipTests clean compile

